import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../AppConfig/components/Header";
import SessionProviderWrapper from "../AppConfig/SessionProviderWrapper";
import LoadingSpinner from "@/AppConfig/components/LoadingSpinner";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProviderWrapper>
          <Suspense fallback={<LoadingSpinner />}>
            <Header />
          </Suspense>
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
